export enum UserRole {
  CUSTOMER = "CUSTOMER",
  SALES = "SALES",
  DEVELOPER = "DEVELOPER",
  ACCOUNT_MANAGER = "ACCOUNT_MANAGER",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
  CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
  MARKETING = "MARKETING",
  CONTENT_MANAGER = "CONTENT_MANAGER",
}

export enum Gender {
  MALE = "M",
  FEMALE = "F",
  OTHER = "O",
}
